---
- name: This playbook for a maven installtion on slave system in ubuntu OS
  hosts: build-slave
  become: true
  tasks:
  - name: update ubuntu system with latest package
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Java on slave system because of Jenkins master. It's configured in java.
    apt:
      name: openjdk-17-jdk
      state: present
  
  - name: Install maven packages from maven installtion url.
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
      dest: /opt

  - name: Unzip maven packages
    unarchive:
      src: /opt/apache-maven-3.9.8-bin.tar.gz
      dest: /opt
      remote_src: yes

  - name: install docker
    apt:
      name: docker.io
      state: present
    
  - name: start docker service
    service:
      name: docker
      state: started